services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: kakeibo_test
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: db
  web:
    environment:
      RAILS_ENV: test
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rspec"
